title: Salty On Security
taxonomies:
  stub: stub
disableKinds:
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    endLevel: 2
    startLevel: 1
disqusShortname: saltyonsecurity-net
domain: saltyonsecurity.net
sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5
params:
  gtm_id: GTM-MQRRPH3
enableEmoji: true