title:  Salty On Security
baseURL: /
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
disqusShortname: saltyonsecurity-net
googleAnalytics: G-WFY115RLD3