title:  Salty On Security
baseURL: /
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
disqusShortname: saltyonsecurity-net
googleAnalytics: G-WFY115RLD3
params:
  googlefonts:
    - - Source Sans Pro
      - '400, 700'
    - - Source Serif Pro
      - '400, 400i, 700, 700i'
  heading_font: Source Sans Pro
  body_font: Source Serif Pro
  monospace_font: Source Code Pro