title:  Salty On Security
baseURL: /
taxonomies:
  stub: stub
disableKinds:
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
disqusShortname: saltyonsecurity-net
gtm_id: G-WFY115RLD3
domain: saltyonsecurity.net

sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5