title: Salty On Security
taxonomies:
  stub: stub
disableKinds:
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
disqusShortname: saltyonsecurity-net
domain: saltyonsecurity.net
sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5
params:
  gtm_id: G-WFY115RLD3