title:  Salty On Security
baseURL: /
taxonomies:
  stub: stub
disableKinds:
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
disqusShortname: saltyonsecurity-net
googleAnalytics: G-WFY115RLD3
author:
  name: Dylan Evans
copyright: This work is licensed under a Creative Commons Attribution-ShareAlike 4.0
  International License.
languageCode: en-us